version: '3.7'
services:
  backend1:
    build:
      context: app
      dockerfile: Dockerfile
    command: python /app/app.py
    tty: true
    environment:
      PYTHONPATH: .
    ports:
      - 3991:3991  
  backend2:
    build:
      context: app
      dockerfile: Dockerfile
    command: python /app/app.py
    tty: true
    environment:
      PYTHONPATH: .
    ports:
      - 3993:3991
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3992:80
    depends_on:
      - "backend1"
      - "backend2"
