version: '3.7'
services:
  backend:
    build:
      context: app
      dockerfile: Dockerfile
    command: python /app/app.py
    tty: true
    environment:
      PYTHONPATH: .
    ports:
      - 3991:3991
